# Generated by Django 3.1.3 on 2020-11-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='date_completed',
            new_name='datecompleted',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo_creator',
            new_name='user',
        ),
    ]
